# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

variables:
  BuildConfiguration: Release
  SignType: real
  TeamName: vssetup

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pr: none

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: AzurePipelinesWindows2022compliantGPT
      policheck:
        enabled: true
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true # BinSkim scans whole source tree but we only need to scan the output dir.

    stages:
      - stage: Build
        jobs:
          - job: Build
            templateContext:
              mb:
                signing:
                  enabled: true
                  signType: $(SignType)

            steps:
              - checkout: self
                fetchDepth: 0 # avoid shallow clone so nbgv can do its work.

              - template: /build.yml@self
                parameters:
                  BuildConfiguration: $(BuildConfiguration)
