# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

variables:
  BuildConfiguration: Release
  TeamName: vssetup

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pr: none

schedules:
- cron: "0 12 * * 1"
  displayName: 'Run every Monday at 12:00 p.m.'
  branches:
    include:
    - main
  always: true

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: AzurePipelinesWindows2022compliantGPT
      policheck:
        enabled: true
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true # BinSkim scans whole source tree but we only need to scan the output dir.
    stages:
      - stage: Compliance
        jobs:
          - job: Compliance
            steps:
              - template: /build.yml@self
                parameters:
                  BuildConfiguration: $(BuildConfiguration)
