# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

name: PR Build

on: [ pull_request ]

env:
  # Path to the project source.
  PROJECT_PATH: VSConfigFinder

  # Path to the test project source.
  TEST_PROJECT_PATH: VSConfigFinder.Test

  # Configuration type to build.
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        global-json-file: global.json
    
    - name: Restore dependencies
      run: dotnet restore --source https://api.nuget.org/v3/index.json
    
    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.PROJECT_PATH }}
    
    - name: Test
      run: dotnet test --verbosity normal --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.TEST_PROJECT_PATH }}

    - name: Publish
      run: dotnet publish --no-build --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.PROJECT_PATH }}
